// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCefjKFu8qspvV_g4z7Zip4FAuaAXJkGUQ',
    appId: '1:615015916490:web:b769b1a71a339d97d1e533',
    messagingSenderId: '615015916490',
    projectId: 'farmer-project-b6282',
    authDomain: 'farmer-project-b6282.firebaseapp.com',
    storageBucket: 'farmer-project-b6282.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5X2kBm8JV-6r5VZanmLcGbondfct0KJw',
    appId: '1:615015916490:android:f34366c3562be2b3d1e533',
    messagingSenderId: '615015916490',
    projectId: 'farmer-project-b6282',
    storageBucket: 'farmer-project-b6282.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA174W8b8Wa4oRZD6L9lZ3jE-5qWJZmD0Q',
    appId: '1:615015916490:ios:bd7fd28357cf08dad1e533',
    messagingSenderId: '615015916490',
    projectId: 'farmer-project-b6282',
    storageBucket: 'farmer-project-b6282.appspot.com',
    iosBundleId: 'com.example.farmerProject',
  );
}
